### ISSUE TITLE
Why are sessionSymbols considered suspicious?

### ISSUE THREAD

**Issue by kenkangxgwe** [WolframResearch/codeinspector#12]
I recently noticed that codeInspector gave warnings about `Quit`, `Echo` and other so-called SessionSymbols [here](https://github.com/WolframResearch/codeinspector/blob/986ab4fa7782091cc613eae8b4972baf2bc39733/WolframLanguageSyntax/Data/SessionSymbols.wl). I wonder what those warnings are about? One thing that I can think of is that these symbols are often for debugging during development, so the warning is there to remind users that there are debug symbols and should not be included in the final package?

**Comment by bostick** [comment]
`Quit`, `Echo`, etc. are considered suspicious in package code because they are generally not intended to be in package code, and their presence is a bug.

This can happen because they were left in during debugging

This can also happen because code is copied from a notebook, where it is more acceptable to use `Quit`, `Echo`, etc.

The presence of these symbols is not always a problem, which is why this rule has confidence of 0.55.

Right now, the rule is only looking at the presence of the symbol itself.

When more specific patterns are developed and the context of the symbols in the surrounding code is better understood, then there will be fewer false positives and I will increase the confidence in the rule.

**Comment by szhorvat** [comment]
This is useful. I've left a stray `Echo` in there before.
